# Generated by Django 4.0.3 on 2022-04-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayplan', '0002_remove_plans_year_in_school_plans_grupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='grupa',
            field=models.CharField(choices=[('OS', 'Osobiste'), ('PR', 'Praca'), ('SZ', 'Szkola')], default='OS', max_length=2),
        ),
    ]
