# Generated by Django 4.0.3 on 2022-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayplan', '0003_alter_plans_grupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='czas',
            field=models.CharField(default='01:00', max_length=5),
        ),
    ]
