# Generated by Django 4.0.3 on 2022-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayplan', '0005_plans_zrobione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='zrobione',
            field=models.CharField(choices=[('TAK', 'Tak'), ('NIE', 'Nie')], max_length=3),
        ),
    ]
