# Generated by Django 4.0.3 on 2022-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayplan', '0006_alter_plans_zrobione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='zrobione',
            field=models.CharField(choices=[('tak', 'Tak'), ('nie', 'Nie')], max_length=3),
        ),
    ]
