# Generated by Django 4.0.3 on 2022-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Czwartek',
            field=models.CharField(default='07:00-15:40', max_length=11),
        ),
        migrations.AddField(
            model_name='school',
            name='Piatek',
            field=models.CharField(default='07:00-15:40', max_length=11),
        ),
        migrations.AddField(
            model_name='school',
            name='Sobota',
            field=models.CharField(default='07:00-15:40', max_length=11),
        ),
        migrations.AddField(
            model_name='school',
            name='Sroda',
            field=models.CharField(default='07:00-15:40', max_length=11),
        ),
        migrations.AddField(
            model_name='school',
            name='Wtorek',
            field=models.CharField(default='07:00-15:40', max_length=11),
        ),
        migrations.AlterField(
            model_name='school',
            name='Poniedzialek',
            field=models.CharField(default='07:00-15:40', max_length=11),
        ),
    ]
